{
    "title":"eyl compiler setting UI",
    "up_set": "Update Settings",
    "ex_an_sa":"save and exit",
    "bk_an_sa":"save and back",
    "reload":"reload",
    "lang_name":"language",
    "lang_cn": "Chinese Simplified",
    "lang_us": "English",
    "lang_ft": "Chinese Traditional Chinese",
    "lang_fe": "French",
    "lang_ru": "Russian",
    "eyl_version":"EYL main program version",
    "load_value": "File loading... Finish! ",
    "lang_set_zh_cn": "Set the language to Chinese (Simplified)",
    "lang_set_zh_ft": "Set the language to Chinese (traditional)",
    "lang_set_us": "Set the language to English",
    "lang_set_fe": "Set the language to French",
    "lang_set_ru": "set the language to Russian",
    "Help_Lister": "Help - Get Help  Emplint - Print Text or Variables  Necht or Exeter () - Exit Program Ensetin - Enter Settings Choi  Nifsen - View Version ( - View Hellp File Version)",
    "keyerror":"keyword error, the exception occurs mainly in the dictionary, may be trying to access a key that does not exist in the dictionary",
    "syntaxerror": "There is an error in the syntax, the compiler stops running",
    "typeerror": "Type error, an action or function may be applied to an object of an inappropriate type",
    "indexerror":"Index error, it may be that the subscript index exceeds the sequence boundary",
    "valueerror": "The value is wrong, it may be that the user passed in a value that the caller did not expect, or that the value is of the correct type, but wants to get an index of a non-existent value in a list",
    "attributeerror": "Attribute error, it may be that the user is trying to access a property that does not exist for an object, or that an incorrect method has been used for an object",
    "nameerror":"Variable name is incorrect, please check",
    "FileNotfoundError": "Error opening file, may have opened a file that does not exist or is empty",
    "stopIteration": "The iterator error, it may be that the last value of the iterator is still accessed, and this exception is raised, so the user is reminded that there is no value in the iterator that is accessible",
    "assertionError": "Assertion error, which may be caused by a false expression detected by an assertion sentence when the user uses an assertion sentence to detect an exception",
    "eoferror": "Input error, it may be that a stop command was received during the input",
    "keyboardinterrupt": "There is no error in the code, just a human intervention with the Ctrl+C key to stop it"
}